// Barrel export — tous les hooks React Query splittés par domaine
export * from './queries/homes'
export * from './queries/cases'
export * from './queries/appointments'
export * from './queries/diagnostics'
export * from './queries/profiles'
export * from './queries/articles'
export * from './queries/contacts'
export * from './queries/dashboard'
export * from './queries/health'
export * from './queries/partners'
