import type { TenantFeatures, PricingTier } from './tenant.types'

export const TIER_FEATURES: Record<PricingTier, TenantFeatures> = {
  starter: {
    publicDiagnostic: true,
    publicArticles: true,
    publicAssistantAI: false,
    portalPro: true,
    portalParticulier: false,
    aiChiffrage: false,
    aiAssistantTechnique: false,
    recruitmentPyramid: false,
    socialMediaPosts: false,
    badgesGamification: false,
    catalogueCadeaux: false,
    qrCodeGeneration: true,
    monthlyPdfReport: false,
    notifications: true,
    crmWebhook: false,
    emailNotifications: true,
    simulationLinks: false,
    teamStats: false,
  },
  pro: {
    publicDiagnostic: true,
    publicArticles: true,
    publicAssistantAI: true,
    portalPro: true,
    portalParticulier: true,
    aiChiffrage: true,
    aiAssistantTechnique: true,
    recruitmentPyramid: false,
    socialMediaPosts: true,
    badgesGamification: true,
    catalogueCadeaux: true,
    qrCodeGeneration: true,
    monthlyPdfReport: true,
    notifications: true,
    crmWebhook: true,
    emailNotifications: true,
    simulationLinks: true,
    teamStats: true,
  },
  enterprise: {
    publicDiagnostic: true,
    publicArticles: true,
    publicAssistantAI: true,
    portalPro: true,
    portalParticulier: true,
    aiChiffrage: true,
    aiAssistantTechnique: true,
    recruitmentPyramid: true,
    socialMediaPosts: true,
    badgesGamification: true,
    catalogueCadeaux: true,
    qrCodeGeneration: true,
    monthlyPdfReport: true,
    notifications: true,
    crmWebhook: true,
    emailNotifications: true,
    simulationLinks: true,
    teamStats: true,
  },
}
